<<<<<<< HEAD
# Generated by Django 6.0 on 2025-12-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
=======
# Generated by Django 6.0 on 2025-12-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
>>>>>>> 3d5c8dafa1c7522f9648891421193305a5191b1e
