# Generated by Django 6.0 on 2026-01-19 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_remove_userprofile_level_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='badges/')),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.chapter'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='xp_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chapter_images/'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.achievement'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='earned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.badge'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, to='learning.badge'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement', 'badge')},
        ),
    ]
